// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANjDYCQMFriTVmnl-uhJ68WGPZArW9PO4',
    appId: '1:718442296538:web:4bd970a00cacc569a6e1e3',
    messagingSenderId: '718442296538',
    projectId: 'medieaseapp',
    authDomain: 'medieaseapp.firebaseapp.com',
    storageBucket: 'medieaseapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi0awkHwMON1GYwjjYdbiAtkH7TT8FM-4',
    appId: '1:718442296538:android:091501ea78aee866a6e1e3',
    messagingSenderId: '718442296538',
    projectId: 'medieaseapp',
    storageBucket: 'medieaseapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvjl841874ybUc8TLlQeJwEPMrdzlPmSk',
    appId: '1:718442296538:ios:8d76c5cffa55f245a6e1e3',
    messagingSenderId: '718442296538',
    projectId: 'medieaseapp',
    storageBucket: 'medieaseapp.firebasestorage.app',
    iosBundleId: 'com.example.medieaseApp',
  );
}
